### ISSUE TITLE
HTVNotificationNoSourcesFound not calling first time

### ISSUE THREAD

**Issue by kiranvarma** [heartv/hearTV-iOS-Framework#1]
Team, 

We are trying to integrate the HearTV to our application, In the ViewDidLoad we registered the Notification, But when we run the application for the first time we are not able to get the "noSourcesFound:" method (HTVNotificationNoSourcesFound), But when i go to background and come back we are getting the Notication called. 

We are using Xcode 8 and iOS10

**Comment by namannik** [comment]
I didn't get a chance to look into this today, but I'll look into it early next week and let you know what I find.

**Comment by namannik** [comment]
I haven't been able to duplicate this in the demo app included in this repo.  A couple questions for you:

1. In your app, are you calling `[hearTV start]` before or after registering for the `HTVNotificationNoSourcesFound` notification?  It's best to register the notification first and then call `[hearTV start]`.

2. Are you using the most recent version of the hearTV framework?

**Comment by namannik** [comment]
@kiranvarma , are you still experiencing this issue?

**Comment by kiranvarma** [comment]
Yes some times we are still facing the issue, Some times no notification is called.

**Comment by namannik** [comment]
Has this issue been resolved?  If not, what version of the hearTV Framework are you using?

We released version 2.0 of the framework today, so you might want to update.  This version will be required to stream audio from hearTV devices running firmware version 6.0, which we expect to release in the next week or two.
