### ISSUE TITLE
How to get Device Name based on Mac Address

### ISSUE THREAD

**Issue by CRMAdvantage** [heartv/hearTV-iOS-Framework#3]
Team,

Is there any way to play Audio based on Mac Address (get device name based on Mac address), now API is supporting by name, Actually as per requirement we are changing the name, so mac adress is the only source, how can we do it

**Comment by namannik** [comment]
The framework doesn't support starting an audio stream by MAC address because a hearTV system may have more than one audio input. This is the case for our new product, the hearTV Pro 8X, which has 8 audio inputs. Because it's one device, all 8 inputs share the same MAC address.

The framework is designed around the concept of devices and sources. A device represents a physical piece of hearTV hardware on the local network, and a source represents an audio input on the device. Keep this in mind when designing for your use-case.

**Comment by CRMAdvantage** [comment]
Thank you namannik

**Comment by namannik** [comment]
You're welcome.  Let me know if this becomes a limiting factor for your use-case.  If necessary, we may be able to implement something like this:

`+(void)startPlayingDevice:(HTVDevice*)device inputIndex:(int)index;`

**Comment by CRMAdvantage** [comment]
We configure devices with different names, When we get them we compare them based on the mac address, Based on that we thought getting the local name with mac address and play it.

**Comment by namannik** [comment]
Where do you store your custom source names?  Are they located in an external database with the associated MAC address?

If you leave the hearTV device's source name as the default (`hearTV-xxxx`), you can determine the source name from the last four digits of the MAC address in your database.  For example, a device with a MAC address of `78:A3:51:02:8A:B5` will have a default source name of `hearTV-8AB5`.  For devices that have multiple inputs, the input number is added to the end.  For example, if the MAC address above had 8 inputs, the default source names would be `hearTV-8AB5-1` through `hearTV-8AB5-8`.

**Comment by CRMAdvantage** [comment]
Yes we store in local data base, hearTV-8AB5-1, the last "-1" is index? Of the device, Actually we are connecting multiple devices to one Device and connecting over Wifi. How can we identify the index, Is it  Array Index

**Comment by namannik** [comment]
If you're using hearTV Pro, the source name will be formatted as `hearTV-8AB5`.  This is true regardless of how many hearTV Pros you've connected together.  For example, if you configure one hearTV Pro to create a Wi-Fi network, and two hearTV Pros to join the first unit's Wi-Fi network, you will have three completely different source names, such as `hearTV-8AB5`, `hearTV-A2B4`, and `hearTV-5276`.

If you're using hearTV Pro 8X, the source names will be formatted as `hearTV-8AB5-1` through `hearTV-8AB5-8`.

You may be interested in another project we're currently working on for this framework.  We're developing functionality that will enable you to change the hearTV device's settings programmatically through the API.  If you're able to set the device's name using the API, would you still need to store a custom name in your database?

**Comment by CRMAdvantage** [comment]
I got it, We are using hearTV Pro, we are connecting Two devices to one device, I will try and get back to you if we have any other issues.

**Comment by namannik** [comment]
The more I think about this, I think you'd be better off doing something like this:

1. Retrieve the array of devices available on the local network using `[hearTV devices]`.
2. Iterate through the array to find the device whose `deviceID` matches the MAC address you're looking for.
3. Retrieve the source name from the device using the `sourceNames` property of the device.
4. Use `startPlayingSourceNamed` with the source name retrieved in step 3.

**Comment by namannik** [comment]
As a follow up to my last comment, the reason this method is better is that it would still work if the source's name changes for some reason.
